### ISSUE TITLE
Using your own lufi.conf.template?

### ISSUE THREAD

**Issue by ldidry** [YunoHost-Apps/lufi_ynh#14]
Is it really a good idea? It helps to make sed more easy, but you may miss some updates on lufi.conf.template.

It's just a thought, I'm not fully against the idea, but i think it could be useful to discuss it a little bit, don't you think?

**Comment by ldidry** [comment]
You are already missing `hypnotoad.workers`, `hypnotoad.clients` and `htpasswd` parameters by the way

**Comment by magikcypress** [comment]
It had been coded for ease :) But I have to revisit this when I go to integrate LDAP #3.
By the way, it is not a good idea to use a template.

Thanks

**Comment by kay0u** [comment]
Since #22 we use it now
