### ISSUE TITLE
cannot stat ‘lufi-master-7db7688bc1e8bbe206f6717c98ece78d6e6a05fe/.’

### ISSUE THREAD

**Issue by franzos** [YunoHost-Apps/lufi_ynh#15]
I'm having trouble with the installation of Lufi. 

```
root@YunoHost:/# sudo yunohost app install https://github.com/YunoHost-Apps/lufi_ynh.git
Available domains:
- host.noho.st
Choose a domain for Lufi (default: host.noho.st): 
Choose a path for Lufi (default: /lufi): 
Choose the Lufi administrator (must be an existing YunoHost user): user
Uploading images is it public? [Yes | No] (default: No): 
Warning: usage: yunohost tools [-h]
Warning:                       {upgrade,ldapinit,postinstall,maindomain,update,adminpw,diagnosis}
Warning:                       ...
Warning: yunohost tools: error: invalid choice: 'port-available' (choose from 'upgrade', 'ldapinit', 'postinstall', 'maindomain', 'update', 'adminpw', 'diagnosis')
Warning: 2017-05-13 00:23:32 URL:https://framagit.org/luc/lufi/repository/archive.zip?ref=master [1933809/1933809] -> "lufi.zip" [1]
Warning: FINISHED --2017-05-13 00:23:32--
Warning: Total wall clock time: 3.6s
Warning: Downloaded: 1 files, 1.8M in 3.1s (613 KB/s)
Warning: cp: cannot stat ‘lufi-master-7db7688bc1e8bbe206f6717c98ece78d6e6a05fe/.’: No such file or directory
Error: Installation failed
```

Here's what else I've discovered:
1. Lufi shows up on the 'Desktop' but results in 404 Not Found
2. Browsing installed applications under `/yunohost/admin/#/apps`, Lufi doesn't show up
3. Trying to updaye Lufi, I ger an error `Error: lufi is not installed`

**Comment by magikcypress** [comment]
i see an error with yunohost firewall `yunohost tools` https://github.com/YunoHost-Apps/lufi_ynh/blob/master/scripts/.fonctions#L122, this command search a free port, by default 8095.

You don't use version 2.5 of YunoHost?

**Comment by franzos** [comment]
@magikcypress I'm running 2.5 on a Raspberry Pi 3. Basically just installed this yesterday - so all is clean and fresh :)

**Comment by ldidry** [comment]
It may be a good thing to not compare ynh version as string but as number in https://github.com/YunoHost-Apps/lufi_ynh/blob/master/scripts/.fonctions#L112, what do you think @magikcypress ?

**Comment by franzos** [comment]
I just checked again, apparently I'm running 2.5.6.

yunohost 2.5.6
yunohost-admin 2.5.1
moulinette 2.5.2
ssowat 2.6.6 

Does this make a difference? I noticed that the string is looking for `[ YNH_VERSION = "2.5" ];`

**Comment by ldidry** [comment]
Exactly my point: the comparison should be `if [ YNH_VERSION -ge 2.5 ]; then`.

**Comment by magikcypress** [comment]
Yes, but no ;) I will change port detection with a clean helper.

**Comment by magikcypress** [comment]
We have another problem with this app. 

> Warning: cp: cannot stat ‘lufi-master-7db7688bc1e8bbe206f6717c98ece78d6e6a05fe/.’: No such file or directory

During the installation, we use the following url https://framagit.org/luc/lufi/repository/archive.zip?ref=master to download the source of lufi. But if the master changes, the download of the sources fails? @ldidry , you don't keep the release or the old master on Gitlab?

**Comment by ldidry** [comment]
If the master change, the SHA hash of the last commit changes, so do the directory name. So it will not be `lufi-master-7db7688bc1e8bbe206f6717c98ece78d6e6a05fe` anymore.

Possible workarounds:
- specify the commit when downloading the zip: https://framagit.org/luc/lufi/repository/archive.zip?ref=7db7688bc1e8bbe206f6717c98ece78d6e6a05fe
- make a `mv lufi-master* lufi-master`

**Comment by frju365** [comment]
Did the PR work ? Can we close this issue ? @franzos, can you confirm it works ?

**Comment by frju365** [comment]
The PR works for me.
