### ISSUE TITLE
Open in private mode ||| Ouvert en mode privé

### ISSUE THREAD

**Issue by MyNameIsTroll** [YunoHost-Apps/lufi_ynh#21]
Salut, 
Lorsque j'installe Lufi depuis l'interface YunoHost en sélectionnant le mode "privé", même quand je suis déconnecté de YunoHost je peux continuer d'uploader des fichiers. J'ai essayé en vidant le cache, les cookies etc... et depuis plusieurs terminaux c'est pareil. Est-ce normal ? 

[EN ] Hi, 
When I install Lufi from the YunoHost interface by selecting"private" mode, even when I am disconnected from YunoHost I can continue uploading files. I tried emptying the cache, cookies etc... and since several terminals it's the same. Is that normal?

**Comment by kay0u** [comment]
Salut, #22 va fixer cette issue en utilisant ldap.

Merci pour ton report!

[EN]
Hi, #22 will fixed this by using ldap.

That you for your report btw!

**Comment by kay0u** [comment]
#22 has been merged, I close this issue.

Feel free to reopen it if needed
