### ISSUE TITLE
lufi failing to start or upgrade : Perl_xs_apiversion_bootcheck

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/lufi_ynh#24]
```
Mar 23 10:47:25 yunohost carton[586]: /usr/bin/perl: symbol lookup error: /var/www/lufi/local/lib/perl5/x86_64-linux-gnu-thread-multi/auto/Net/SSLeay/SSLeay.so: undefined symbol: Perl_xs_apiversion_bootcheck
```

**Comment by ldidry** [comment]
That may happen when openssl have changed. That usually solves the problem:
```
rm -rf local
carton install
```

**Comment by arthurlutz** [comment]
I tried to do the `rm -rf local` then go through the upgrade lufi via yunohost (was afraid of running `carton install` as root). 

It failed to start and I found some stuff about liborllite, installed liborlite-perl, then got an error mail. So I stopped and tried the carton install command, I got : 

```
root@yunohost:/var/www/lufi# carton install
Installing modules using /var/www/lufi/cpanfile
! Configure failed for File-Remove-1.52. See /root/.cpanm/work/1553357425.21738/build.log for details.
! Configure failed for ORLite-1.98. See /root/.cpanm/work/1553357425.21738/build.log for details.
! Configure failed for perl-ldap-0.65. See /root/.cpanm/work/1553357425.21738/build.log for details.
! Configure failed for MIME-Charset-1.012. See /root/.cpanm/work/1553357425.21738/build.log for details.
! Installing the dependencies failed: Module 'MIME::Charset' is not installed
! Bailing out the installation for MIME-EncWords-v1.014.3.
! Installing the dependencies failed: Module 'MIME::EncWords' is not installed
! Bailing out the installation for Mojolicious-Plugin-Mail-1.5.
! Installing the dependencies failed: Module 'Mojolicious::Plugin::Mail' is not installed
! Bailing out the installation for /var/www/lufi/.
Installing modules failed

```

**Comment by ldidry** [comment]
Can you give the content of /root/.cpanm/work/1553357425.21738/build.log please?

**Comment by arthurlutz** [comment]
I found 

```
Configuring Mojolicious-Plugin-Mail-1.5
Running Build.PL
Checking prerequisites...
  requires:
    !  MIME::EncWords is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation
```


`apt install libmime-encwords-perl` seems to solve the problem. Do you still want the full log ?

**Comment by ldidry** [comment]
Yes, please, because MIME::EncWords should be installed as dependency, so it's better if I have the full log to understand why the installation of MIME::EncWords failed.

**Comment by arthurlutz** [comment]
[build.log](https://github.com/YunoHost-Apps/lufi_ynh/files/3002684/build.log)

**Comment by ldidry** [comment]
Je vois le souci : 
```
Can't locate inc/Module/Install.pm
```

C'est un souci qui est apparu avec Stretch (il me semble) et que j'ai résolu dans une version de Lufi ultérieure à la version du paque YNH que tu utilises. Le paquet YNH a été mis à jour dans https://github.com/YunoHost-Apps/lufi_ynh/pull/23 qui a été mergée il y a 16h, donc ça ne devrait plus être un problème.

**Comment by kay0u** [comment]
#23 was merged on testing branch, so you can't access it right now.

However, I'll merge #22 into master soon (tonight or tomorrow). I just have to check some things before

**Comment by kay0u** [comment]
I close this issue since #22 has been merged.

Feel free to reopen it if you still have this problem.
