### ISSUE TITLE
Tune carton install

### ISSUE THREAD

**Issue by ldidry** [YunoHost-Apps/lufi_ynh#25]
See on https://framagit.org/fiat-tux/hat-softwares/lufi/wikis/installation how you can avoid to install unneeded deps (like Mojo::Pg when you use SQLite).

**Comment by kay0u** [comment]
Hi, as you can see in #22, psql is now installed by default. Since there is no migration possible from sqlite to psql, old install will still used sqlite.

But if you say to me that there is no interest to use psql rather sqlite, I can revert to use sqlite

This PR will be merge soon.

**Comment by ldidry** [comment]
There is a command to migrate from SQLite to Pg or MySQL :slightly_smiling_face: :
```
carton exec script/lufi sqliteToOtherDB
```

The help:
```
  Usage: script/lufi sqliteToOtherDB

  This command needs you to:
    - set `db_path` in your config file (otherwise, it will use the default path, `lufi.db` to migrate data from)
    - set `dbtype` to an other database type in your config file
    - configure the other database access in your config file
```

You may want to try it (should work flawlessly but may take time and you may need to test it in YNH scripts).

Anyway, you'll need to install SQLite deps AND the new DB (Pg or MySQL) deps for it, but for the new installations, you may want to install only the needed deps.

Anyway, there's is not only DB deps that you can disable:
```
--without=htpasswd
--without=test
```

And there is an important argument: `--deployment `, that ensures that you install the same versions of the deps that I used and that I know they will work properly.

**Comment by kay0u** [comment]
Thank you for your tips, it will help me a lot!

As you can see I already use `deployment` in the "testing" branch (PR: #22)
But you're right, I can avoid some unused deps with `--without=htpasswd` and `--without=test`

Moreover, `sqliteToOtherDB` will help me a lot!

I'll commit an improvement in my PR soon!

**Comment by kay0u** [comment]
Migration tested at home. Looks good!

**Comment by kay0u** [comment]
I close this issue, #22 merged.

Feel free to open a new one if you see something else to improve!
