### ISSUE TITLE
Build-essential ? Perlmagick ?

### ISSUE THREAD

**Issue by ldidry** [YunoHost-Apps/lufi_ynh#7]
I don't see the installation of build-essential in the install script but see perlmagick.

- Build-essential will likely be required to install the dependencies (it installs make, which is required, and gcc, which can be required, I don't remember if lufi dependencies requires gcc to be installed).
- Perlmagick is not required at all, it is for lutim

**Comment by magikcypress** [comment]
Thanks for this information !

I have a question about uninstalling dependencies found in /root.cpan. I can't use a brutal rm ? Do you have a solution for that?

**Comment by ldidry** [comment]
There is no dependencies in /root/.cpan, it's a folder for build/cache/config, so you can empty it without problem.

But for removing Carton from the system… there is no `cpan uninstall` command. However, you can install `cpanminus` debian package and try `cpanm --uninstall -f Carton` but I don't know if it will remove dependencies.

**Comment by frju365** [comment]
@ldidry, you have now admin right on all your repos.
