### ISSUE TITLE
Why specifying arch_dir?

### ISSUE THREAD

**Issue by ldidry** [YunoHost-Apps/lufi_ynh#9]
On [install, line 104](https://github.com/YunoHost-Apps/lufi_ynh/blob/master/scripts/install#L104), i see that you're adding some stuff on [script/lufi][https://github.com/YunoHost-Apps/lufi_ynh/blob/master/sources/ajouts/script/lufi). What is it for? Carton is supposed to correctly use the `local` folder, you shouldn't have to add `local/lib/perl5/xxx` to `@INC`.

**Comment by magikcypress** [comment]
I do not know? @frju365  you remember why you wrote this code ?
